# Generated by Django 3.2.4 on 2022-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo_producto',
            new_name='tipoproducto',
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombreTipo',
            field=models.CharField(max_length=50, verbose_name='Nombre del tipo'),
        ),
    ]
